main : main.o adder.o sub.o mul.o diver.o
	gcc -o main main.o adder.o sub.o mul.o diver.o

main.o :main.c
	gcc -c main.c
adder.o :adder.c
	gcc -c adder.c
sub.o :sub.c
	gcc -c sub.c
mul.o :mul.c
	gcc -c mul.c
diver.o :diver.c
	gcc -c diver.c
